### ISSUE TITLE
This GitHub Repository Serves No Use

### ISSUE THREAD

**Issue by LogitechGalena** [reb0und/Xplor#2]
Hey, this GitHub repository seems to have no case in which it would be useful. Why?

**Comment by Albinism** [comment]
@reb0und, any idea why?  Its publication seems like a mistake; any idea why it was committed? 

Thanks in advance.

**Comment by reb0und** [comment]
@LogitechGalena @Albinism This is currently a work in progress. What do you find confusing?

**Comment by Albinism** [comment]
Typically, developers reserve publication for repositories which satisfy some basic standard of functionality.  Considering the parameters which you specified in the repository's meta-data, its publication seems somewhat puzzling.

**Comment by reb0und** [comment]
I understand your concern. You can find all the information regarding this project on the [README](https://github.com/reb0und/Xplor#readme). If you have any further questions, feel free to contact me via email.
